user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

info:
    resource: "@InfoBundle/Resources/config/routing.yml"
    prefix:   /
    
admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /
    
cita:
    resource: "@CitaBundle/Controller/"
    type:     annotation
    prefix:   /

entrevista:
    resource: "@EntrevistaBundle/Controller/"
    type:     annotation
    prefix:   /
    
instrudvi:
    resource: "@PruebaBundle/Controller/"
    type:     annotation
    prefix:   /
   
dsagaco:
    resource: "@DsagacoBundle/Resources/config/routing.yml"
    prefix:   /
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

pg_cita:
    path:     /cita/
    defaults: { _controller: CitaBundle:Default:cita}
    
pg_instru_dvi1:
    path:     /pgInstruDVI1/
    defaults: { _controller: PruebaBundle:Default:prueba}    
    
pg_instru_dvi2:
    path:     /pgInstruDVI2/
    defaults: { _controller: PruebaBundle:Default:instruDVI}
    
pg_entrevista:
    path:     /entrevista/
    defaults: { _controller: EntrevistaBundle:Default:entrevista}

pg_info:
    path:     /info/{pagina}/
    defaults: { _controller: InfoBundle:Default:info}
    
pg_rol:
    path:     /rol/
    defaults: { _controller: AdminBundle:Default:rol}
