<?php

namespace sagaco\DsagacoBundle\Entity;

use Doctrine\ORM\EntityRepository;


/**
 * clAreaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class clAreaRepository extends EntityRepository
{
    public function listar(){
        
        /* Columan indexada*/
        $alias = "a";
        
        /* DB tabla a usar */
        $tableObjectName = 'DsagacoBundle:clArea';
        
        /* Campo para ordenar */        
        $txtOrden = 'coArea';
        
        $objConsulta = $this->getEntityManager()
                ->createQuery('SELECT '
                        . $alias .
                        ' FROM '. $tableObjectName .' '. $alias 
                        .' ORDER BY '. $alias .'.'. $txtOrden . ' ASC');
        try {
            return $objConsulta->getArrayResult();  
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }         
    }
}
