<?php

namespace sagaco\DsagacoBundlesagacoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * clAreaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class clAreaRepository extends EntityRepository
{
}
