<?php

namespace sagaco\DsagacoBundle\Entity;

use Doctrine\ORM\EntityRepository;


/**
 * clAsignaMasfacilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class clAsignaMasfacilRepository extends EntityRepository
{
    public function listar(){
        
        /* Columan indexada*/
        $alias = "a";
        
        /* DB tabla a usar */
        $tableObjectName = 'DsagacoBundle:clAsignaMasfacil';
        
        /* Campo para ordenar */        
        $txtOrden = 'coAsignaMasfacil';
        
        $objConsulta = $this->getEntityManager()
                ->createQuery('SELECT '
                        . $alias .
                        ' FROM '. $tableObjectName .' '. $alias 
                        .' ORDER BY '. $alias .'.'. $txtOrden . ' ASC');
        try {
            return $objConsulta->getArrayResult();  
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }         
    }
}
