<?php

namespace sagaco\DsagacoBundle\Entity;

use Doctrine\ORM\EntityRepository;


/**
 * clDetallAgendaorientadorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class clDetallAgendaorientadorRepository extends EntityRepository
{ 
    public function listar(){
        
        /* Columna indexada */
        $alias = "a";
        
        /* DB table a usar */
        $tableObjectName = 'DsagacoBundle:clDetallAgendaorientador';

        /* Campo para ordenar */        
        $txtOrden = 'coDetallAgendaorientador';
        
        $objConsulta = $this->getEntityManager()
                ->createQuery('SELECT '
                        . $alias .
                        ' FROM '. $tableObjectName .' '. $alias 
                        .' ORDER BY '. $alias .'.'. $txtOrden . ' ASC');
        try {
            return $objConsulta->getArrayResult();  
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }         
    }  
    
    public function detalleAgendaPorSemestre($intSemestre, $hHora, $nbCampo, $valCampo){
        
        /* Columna indexada */
        $alias = "a";        
 
        
        /* DB table a usar */
        $tableObjectName = 'DsagacoBundle:clDetallAgendaorientador';
        $tableObjectName2 = 'DsagacoBundle:clDetallAgendaorientador';
        

        /* Campo para ordenar */        
        $txtOrden = 'hoInicio';
        //$hHora = $hour.':'.$minute.':'.$second;
        //$hInicio = $hHora;
        //$hInicio->setTime($hour, $minute, $second);
        //$nbCampo = 'inLunes';
        //$valCampo = '1';
        
        
        //var_dump($hInicio);  
        //die;
        
        $objConsulta = $this->getEntityManager()
                ->createQuery('SELECT'
                        . ' d.coOrientador '
                        . ' FROM '. $tableObjectName .' '. $alias
                        . ' INNER JOIN a.coAgendaOrientador o'
                        . ' INNER JOIN o.coOrientador d'
                        //. ' INNER JOIN d.coOrientador h'
                        . ' WHERE o.coSemestre = :semestre'
                        . ' AND a.hoInicio = :hInicio'
                        . ' AND a.'.$nbCampo.' = :nbCampo'
                        //. ' AND o.coOrientador in (SELECT h.coOrientador '
                        //. ' FROM '. $tableObjectName2 .' h'
                        //. ' WHERE h.hoInicio != :hInicio)'
                        . ' ORDER BY '. $alias .'.'. $txtOrden . ' ASC')
                ->setParameter('semestre', $intSemestre)
                ->setParameter('hInicio', $hHora)
                ->setParameter('nbCampo', $valCampo)
                ;
       //var_dump($objConsulta); die;
        try {
            return $objConsulta->getArrayResult();
           
            
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }         
    }
}
