<?php

namespace sagaco\DsagacoBundle\Entity;

use Doctrine\ORM\EntityRepository;


/**
 * clDetallAgendaorientadorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class clDetallAgendaorientadorRepository extends EntityRepository
{ 
    public function listar(){
        
        /* Columna indexada */
        $alias = "a";
        
        /* DB table a usar */
        $tableObjectName = 'DsagacoBundle:clDetallAgendaorientador';

        /* Campo para ordenar */        
        $txtOrden = 'coDetallAgendaorientador';
        
        $objConsulta = $this->getEntityManager()
                ->createQuery('SELECT '
                        . $alias .
                        ' FROM '. $tableObjectName .' '. $alias 
                        .' ORDER BY '. $alias .'.'. $txtOrden . ' ASC');
        try {
            return $objConsulta->getArrayResult();  
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }         
    }  
    
    public function detalleAgendaPorSemestre($intSemestre){
        
        /* Columna indexada */
        $alias = "a";        
 
        
        /* DB table a usar */
        $tableObjectName = 'DsagacoBundle:clDetallAgendaorientador';

        /* Campo para ordenar */        
        $txtOrden = 'hoInicio';
        
        $objConsulta = $this->getEntityManager()
                ->createQuery('SELECT '
                        . $alias . ', o '
                        .' FROM '. $tableObjectName .' '. $alias
                        .' JOIN a.coAgendaOrientador o'
                        . ' WHERE o.coSemestre = :semestre'
                        .' ORDER BY '. $alias .'.'. $txtOrden . ' ASC')
                ->setParameter('semestre', $intSemestre)
                //->setParameter('feFin', $feFin)
                ;
        try {
            return $objConsulta->getArrayResult();  
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }         
    }
}
