<?php

namespace sagaco\DsagacoBundle\Entity;

use Doctrine\ORM\EntityRepository;


/**
 * clGrupoRolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class clGrupoRolRepository extends EntityRepository
{ 
    public function listar(){
        
        /* Indexed column (used for fast and accurate table cardinality) */
        $alias = "a";
        
        /* DB table to use */
        $tableObjectName = 'DsagacoBundle:clGrupoRol';
        
        /* Campo para ordenar */        
        $txtOrden = 'nbGrupoRol';
        
        $objConsulta = $this->getEntityManager()
                ->createQuery('SELECT '
                        . $alias .
                        ' FROM '. $tableObjectName .' '. $alias 
                        .' ORDER BY '. $alias .'.'. $txtOrden . ' ASC');
        try {
            return $objConsulta->getArrayResult();  
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }         
    }        
}