<?php

namespace sagaco\DsagacoBundle\Entity;

use Doctrine\ORM\EntityRepository;


/**
 * clHorariCitaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class clHorariCitaRepository extends EntityRepository
{ 
    public function fechaCitaPorSemana($feInicio, $feFin){
        
        /* Columna indexada */
        $alias = "a";      
       
        /* DB table a usar */
        $tableObjectName = 'DsagacoBundle:clHorariCita';

        /* Campo para ordenar */        
        $txtOrden = 'feHorario';
        
        $objConsulta = $this->getEntityManager()
                ->createQuery('SELECT '
                        . $alias .
                        ' FROM '. $tableObjectName .' '. $alias 
                        . ' WHERE '. $alias . '.feHorario BETWEEN :feInicio AND :feFin'
                        .' ORDER BY '. $alias .'.'. $txtOrden . ' ASC')
                ->setParameter('feInicio', $feInicio)
                ->setParameter('feFin', $feFin);
        try {
            return $objConsulta->getArrayResult();  
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }         
    }  
}
