<?php

namespace sagaco\DsagacoBundle\Entity;

use Doctrine\ORM\EntityRepository;


/**
 * clMotivoConsultaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class clMotivoConsultaRepository extends EntityRepository
{ 
    public function listar(){
        
        /* Columna indexada */
        $aliasTabla1 = "a";
        $aliasTabla2 = "b";
        
        /* DB table a usar */
        $tableObjectName = 'DsagacoBundle:clMotivoConsulta';

        /* Campo para ordenar */        
        $txtOrden = 'coMotivoConsulta';
        
        $objConsulta = $this->getEntityManager()
                ->createQuery('SELECT '
                        . $aliasTabla1 .', '.$aliasTabla2
                        .' FROM '. $tableObjectName .' '. $aliasTabla1 
                        .' JOIN '. $aliasTabla1 .'.coArea '. $aliasTabla2                        
                        .' ORDER BY '. $aliasTabla1 .'.'. $txtOrden . ' ASC');
        try {
            return $objConsulta->getArrayResult();  
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }         
    }  
}