<?php

namespace sagaco\DsagacoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * clPruebaDVIRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tb_prueclPruebaDVIRepositoryba_dviRepository extends EntityRepository
{
}
