<?php

namespace sagaco\DsagacoBundle\Entity;

use Doctrine\ORM\EntityRepository;


/**
 * clTipoEntrevistaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class clTipoEntrevistaRepository extends EntityRepository
{ 
    public function listar(){
        
        /* Indexed column (used for fast and accurate table cardinality) */
        $alias = "a";
        
        /* DB tabla a usar */
        $tableObjectName = 'DsagacoBundle:clTipoEntrevista';
        
        /* Campo para ordenar */        
        $txtOrden = 'coTipoEntrevista';
        
        $objConsulta = $this->getEntityManager()
                ->createQuery('SELECT '
                        . $alias .
                        ' FROM '. $tableObjectName .' '. $alias 
                        .' ORDER BY a.nbTipoEntrevista ASC');

        try {
            return $objConsulta->getArrayResult();  
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }         
    }
}