parameters:
#    Dsagaco.example.class: sagaco\DsagacoBundle\Example

services:
#    Dsagaco.example:
#        class: %Dsagaco.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
