parameters:
#    entrevista.example.class: sagaco\EntrevistaBundle\Example

services:
#    entrevista.example:
#        class: %entrevista.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
